### ISSUE TITLE
changelog in a subfolder

### ISSUE THREAD

**Issue by fibo** [th0r/npm-upgrade#11]
Hi,

my changelog is https://github.com/fibo/algebra/blob/master/gh-pages/changelog.md

Can npm-upgrade support it?

A part that the filename is not in the list of *known* changelog filenames, it is in a subfolder.
In particular, I want the changelog to be available on GitHub Pages project website, hence it is in a subfolder.

**Comment by th0r** [comment]
You can either add `"changelog": "https://github.com/fibo/algebra/blob/master/gh-pages/changelog.md"` field to your `package.json` and publish new version of your package or make a PR adding this url to the list of custom changelogs.
See [here](https://github.com/th0r/npm-upgrade#troubleshooting) for more info.

**Comment by fibo** [comment]
Thanks, I will add the package.json field.

It would be great if there were some official changelog field, I guess it could be `repository.changelog` and it should be filled with an URL.
