### ISSUE TITLE
`npm 3` progress bar appears during upgrade process

### ISSUE THREAD

**Issue by th0r** [th0r/npm-upgrade#13]
Setting `progress = false` config setting should fix it.

**Comment by tarunbatra** [comment]
Can't see the 4th option due to the progress bar.
![screenshot from 2016-09-21 02-00-36](https://cloud.githubusercontent.com/assets/5329230/18687899/c12566e2-7f9f-11e6-9025-4728ccf3c809.png)
Any idea what is causing this progress bar to appear constantly?

**Comment by th0r** [comment]
> Can't see the 4th option due to the progress bar.

Until I fix this bug you can temporary fix it by adding `progress = false` option your `.npmrc` file.
It will also [significantly speed up](https://github.com/npm/npm/issues/11283) `npm install` command.

**Comment by tarunbatra** [comment]
Thanx. Already running using temporary fix. Maybe I can help you with the fix.

**Comment by th0r** [comment]
> Maybe I can help you with the fix.

It would be great) I just don't have enough time now.

**Comment by th0r** [comment]
Fixed in `v1.0.1`
