### ISSUE TITLE
No arrow key moves

### ISSUE THREAD

**Issue by Simoneth** [th0r/npm-upgrade#15]
I tried  npm-upgrade

the arrow it doesn't move but I can hit enter for Yes.

I tried on Win64bit using Cygwin

**Comment by th0r** [comment]
Hmm, interactive prompt is powered by [Inquirer.js](https://github.com/SBoudrias/Inquirer.js) and I don't do anything special there.

Seems like it's better to fill an issue there.

**Comment by th0r** [comment]
Could you try latest version (`v1.1.0`) where I've updated all deps including `Inquirer.js`?

**Comment by th0r** [comment]
Seems like [Inquirer.js](https://github.com/SBoudrias/Inquirer.js) issue.
