### ISSUE TITLE
'report' command

### ISSUE THREAD

**Issue by andreawyss** [th0r/npm-upgrade#17]
It would be useful to have a 'report' command that just outputs the 'tables with update info' but does not require user interaction. Same as 'check' command but with automatic finish and no update. 
One can then use it in CI tools to remind us of packages that should be upgraded. 

As a workaround for now one can pipe ctrl-C before invoking npm-upgrade
printf '^C' | npm-upgrade

**Comment by th0r** [comment]
Why can't you use [npm-check-updates](https://github.com/tjunnone/npm-check-updates) for this task?

**Comment by steveoh** [comment]
or npm outdated. might as well close this.

**Comment by andreawyss** [comment]
npm outdated or yarn outdated do just that. Thank you
