### ISSUE TITLE
Exits dialog too soon (after first interaction)

### ISSUE THREAD

**Issue by bernardodesousa** [th0r/npm-upgrade#20]
Hi! When I run `npm-upgrade`, after I choose what to do with the first dependency, the process shows me the dialog to choose what to do with the next one, but it also exits the program, giving me the command prompt again. Should I use another key instead of enter?

// npm-upgrade 1.3.0
// Windows 10 64
// Node 10.7.0
// npm 6.2.0

**Comment by th0r** [comment]
What shell do you use?

**Comment by th0r** [comment]
I've just published `v1.4.0` with updated dependencies. Could you try it?

**Comment by bernardodesousa** [comment]
I just tested the 1.4.0 version in a Linux terminal and it works perfectly. Tomorrow, I'll try again on a Node terminal on Windows and report back. Thank you, th0r!

**Comment by th0r** [comment]
@bernardodesousa so, does it work?

**Comment by bernardodesousa** [comment]
It did, and I completely forgot to report. 7 months! Sorry :(
