### ISSUE TITLE
ERROR: Error loading package.json: Unexpected token } in JSON at position 766

### ISSUE THREAD

**Issue by lacymorrow** [th0r/npm-upgrade#23]
Looking into a fix

**Comment by lacymorrow** [comment]
Probably not but it's the best info I have. I try to fix it myself.

**Comment by th0r** [comment]
Why you can't post contents of this package.json? Seems like it's broken. Maybe you have left some JS comments inside of it?

**Comment by lacymorrow** [comment]
Mobile makes things trickier. Here's the sample:
...
  "dependencies": {
    "@zeit/next-source-maps": "0.0.2",
    "express": "^4.16.3",
    "isomorphic-unfetch": "^2.1.1",
    "next": "*",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "rebass": "^2.1.0",
    "styled-components": "^3.4.2"
  },
  "devDependencies": {
    "ava": "^0.25.0",
    "babel-polyfill": "^6.26.0"
  }
...

after updating manually, but I tried setting values as "*" and "Latest"
before giving up



Lacy Morrow
www.lacymorrow.com

**Comment by lacymorrow** [comment]
Never was, I didn't put a whole lot of time into a fix.

The workaround: replace the version numbers of all your dependencies with `*` and delete the `node_modules` folder. Then `npm --save install` to install all the latest versions of the packages.
