### ISSUE TITLE
Update lock file after update

### ISSUE THREAD

**Issue by jcousins-ynap** [th0r/npm-upgrade#26]
After running

```sh
npx npm-upgrade
```
running
```sh
npm ci
```
fails as the lock file is out-of-date (storybook dependency example)
```sh
npm ERR! Invalid: lock file's @storybook@5.0.1 does not satisfy @storybook@^5.0.5
```

To rectify this one must either install the modules with those versions, negating the reason to use this package, or use the default `npm i` which will update to the latest minor versions, but this not ideal as this will also update many other packages.

Please consider updating the lock file after a package has been upgraded?

**Comment by th0r** [comment]
Actually, I don't quite follow. `npm-upgrade` just updates versions in `package.json`. To install them and update `package-lock.json` you should run `npm i` after that. Why you don't want to do that?

**Comment by jcousins-ynap** [comment]
I was under the impression that is what `npm-upgrade` would do. Update the versions and the lock file.

`npm ci` is being run in a jenkins pipeline not locally.

**Comment by th0r** [comment]
So, here is the expected update flow:
1. Run `npm-upgrade` and update `package.json`
2. Run `npm i` that will install updated versions locally and update `package-lock.json` correspondingly.
3. Commit update `package.json` and `package-lock.json`
4. Run `npm ci` in jenkins

**Comment by jcousins-ynap** [comment]
Thanks for the confirmation.
