### ISSUE TITLE
Semver issue..

### ISSUE THREAD

**Issue by jkeruzec** [th0r/npm-upgrade#27]
Hi, 

I'm working with this project [mui-datatables npm versions](https://www.npmjs.com/package/mui-datatables?activeTab=versions)
that change it's name convention not a long time ago using the right semver convention
https://semver.org/#spec-item-11

Problem is here : 
![image](https://user-images.githubusercontent.com/3499632/55941322-4b27b080-5c42-11e9-8083-fc1b9e6c7124.png)

And when I try using npm-upgrade, it propose me an older version (and didn't find newer starting with -beta-54
![image](https://user-images.githubusercontent.com/3499632/55941388-6692bb80-5c42-11e9-9449-3112e0f5eb5d.png)

Can you help with that ?
Thanks,

**Comment by th0r** [comment]
Could you try v2.0.0?
