### ISSUE TITLE
-y, --yes option

### ISSUE THREAD

**Issue by williamboman** [th0r/npm-upgrade#3]
Would be nice to have an option that automatically accepts all available upgrades, e.g.;

```sh
$ npm-upgrade -y -p
$ npm-upgrade -y -do
$ npm-upgrade -y
```

**Comment by th0r** [comment]
This utility is targeted only for *interactive* mode. It's just a wrapper around great [npm-check-updates](https://github.com/tjunnone/npm-check-updates) which allows to do exactly what you want (`ncu -u`).

**Comment by williamboman** [comment]
If it's a wrapper module, why hide/disable that functionality of `ncu`? (I just discovered this module, been using `ncu` so far)

**Comment by th0r** [comment]
I just can't see any use-cases for it. Isn't that scary for you to blindly upgrade all of your project dependencies? It can very easily break everything. And this is exactly what this module is trying to solve.

**Comment by williamboman** [comment]
> I just can't see any use-cases for it. Isn't that scary for you to blindly upgrade all of your project dependencies? It can very easily break everything. 

`ncu` respects the semver range doesn't it?

Anyways, for example, on projects with few dependencies it's nice to just upgrade everything instantly, on other projects I have to upgrade a billion `babel-*` deps at once (`$ ncu -u && git checkout -p -- package.json` is quicker than interactively going through each one). I just think it would be nice to be able to avoid having to use two differently named tools for the same task.

**Comment by th0r** [comment]
I think you are just misunderstanding the purpose of both `ncu` and `npm-upgrade`: they update your `package.json`, not the dependencies in `node_modules`.

This is why your `$ ncu -u && git checkout -p -- package.json` command won't do anything.

What you are looking for is `npm up` - it respects semver and updates your `node_modules`.

**Comment by williamboman** [comment]
> I think you are just misunderstanding the purpose of both ncu and npm-upgrade: they update your package.json, not the dependencies in node_modules.

No I understand the purpose of the tools, disregard the semver comment. Not sure what I was thinking.

> This is why your `$ ncu -u && git checkout -p -- package.json` command won't do anything.

But it does. When I want to upgrade all and then selectively disregard certain changes (essentially the same thing as what this module does, just a bit quicker and reversed) I do something like this;
![asada](https://cloud.githubusercontent.com/assets/6705160/11275995/80a3bf48-8ee0-11e5-8074-518d5922ca84.gif)

Going through all those changes sequentially would take much longer and be more exhausting. Note that I lock the dependencies down to a specific version which is probably why I use this tool a bit differently. Having a `-y` option would save me of having to use 2 identical tools, but it might be very edge case idk.

**Comment by th0r** [comment]
> But it does.

Ah, I haven't noticed `-p` flag)

I've just released `v0.6.0` that allows to specify `filter` argument, so you can now call `npm-upgrade 'babel-plugin-* babel-preset-*'` to upgrade only them.
The only thing is I really don't want to add `--yes` flag so you'll have to close your eyes and hit `enter` several times repeatedly =))

**Comment by williamboman** [comment]
Nice! Thanks
