### ISSUE TITLE
Setting Repository

### ISSUE THREAD

**Issue by Barvor** [th0r/npm-upgrade#30]
Would it be possible to enable setting a repository flag (like npm)?

I am currently using a private repo that does not support npm update (thx nexus).

And therefore usually switch to the official npm repo for that.

Could you put that functionality into npm-upgrade?

**Comment by th0r** [comment]
What exactly do you need? Do you want some `--repository-url` flag or it can be an option in `.npm-upgrade.json` file? Or it should read settings from `.npmrc`?

**Comment by Barvor** [comment]
ONe of those. I guess with consistency a --repository flag would suffice, but having it read the .npmrc would als be good. 

If i can choose I would settle for a --repository flag.

Does is not use the settings set in the .npmrc by default?

**Comment by th0r** [comment]
Could you try v2.0.0?

**Comment by Barvor** [comment]
Works like a charm with a custom registry. It takes the .bashrc or bash settings doesnt it?

**Comment by th0r** [comment]
It now mimics the behavior of the `npm` so it should support all the possible ways to specify npm settings.
