### ISSUE TITLE
Ask about @types after asking about the main package

### ISSUE THREAD

**Issue by lorenzodallavecchia** [th0r/npm-upgrade#32]
It would be nice if the tool asked what to do for a package before asking what to do with the corresponding `@types` package.

For example, suppose that I am using yargs in a TypeScript project. If it needs to be updated, it is likely that both `yargs` and `@types/yargs` will need to be updated.

Since the tool walks through the dependencies alphabetically, it will ask about `@types/yargs` before `yargs`. The problem is that the `@types` packages does not have a changelog that can help me understand if the update is safe or needs attention. Ideally, I would like to first review the main package, possibly looking at the changelog, and only then decide on updating the `@types`.

**Comment by th0r** [comment]
Thanks, good idea.

**Comment by th0r** [comment]
Fixed in v2.0.0
