### ISSUE TITLE
It does not actually update the package, just the package.json

### ISSUE THREAD

**Issue by AddictArts** [th0r/npm-upgrade#4]
When I run the latest version it finds the two that need updating and on each one I select yes. It says yes in the console output. Nothing happens and then the package json prompt comes up and a "Y" here does change the file. I am using node v4, npm 3, and npm-upgrade 0.6.1.

Also,

I find that npm upgrade fails often especially node-gyp stuff. So, can there be an option to uninstall and install instead of upgrade. Thanks

**Comment by th0r** [comment]
Yes, it only updates `package.json`. To install updated modules use `npm i` after it.

**Comment by AddictArts** [comment]
OK, Thanks
