### ISSUE TITLE
Cant find changelog URL for eslint-plugin-jsdoc

### ISSUE THREAD

**Issue by wvanderp** [th0r/npm-upgrade#44]
`? Update "eslint-plugin-jsdoc" in package.json from ^22.0.1 to ^22.1.0? Show changelog
Trying to find changelog URL...
Sorry, we haven't found any changelog URL for eslint-plugin-jsdoc module.
It would be great if you could fill an issue about this here: https://github.com/th0r/npm-upgrade/issues
Thanks a lot!`

the github page is here: https://github.com/gajus/eslint-plugin-jsdoc

but it should point to here: https://github.com/gajus/eslint-plugin-jsdoc/releases

**Comment by th0r** [comment]
It works for me:
```
$ npm-upgrade changelog eslint-plugin-jsdoc
Trying to find changelog URL for eslint-plugin-jsdoc...
Opening https://github.com/gajus/eslint-plugin-jsdoc/releases...
```

**Comment by wvanderp** [comment]
It seems to be working now for me as well.

Sorry for the trouble
