### ISSUE TITLE
Upgrade without ask at each packages

### ISSUE THREAD

**Issue by sebtiz13** [th0r/npm-upgrade#48]
Hello thank for your great package

But it's possible to upgrade without ask if i want upgrade on each packages ?
like `npm-upgrade -y` for "yes for all"

**Comment by th0r** [comment]
Maybe https://github.com/raineorshine/npm-check-updates is what you need?

**Comment by th0r** [comment]
@sebtiz13?

**Comment by sebtiz13** [comment]
Yes it's an feature like 

`ncu -u`

what i talking about

**Comment by th0r** [comment]
But why don't use `ncu` then?

**Comment by th0r** [comment]
But why don't use `ncu` then? Anyway, it's a duplicate of https://github.com/th0r/npm-upgrade/issues/3 - you can find all the reasons there.

**Comment by sebtiz13** [comment]
sorry i didn't know ncu but your reasons in #3 are good and indeed it's better to check all package updated in some many case, but in my case was for automation. So I have note for ncu.

Thanks for the discovery and sorry for duplicate.
