### ISSUE TITLE
Usage with custom registry

### ISSUE THREAD

**Issue by s-pic** [th0r/npm-upgrade#53]
I am pointing npm to another registry ([verdaccio](https://github.com/verdaccio/verdaccio)) by running
```
npm set cafile <local/path>/ca-certificates.crt
$ npm set registry https://npm-registry.foo.bar.com:1337/
$ npm login
```
Using the private registry works like charm.

If I run npm-upgrade, it throws 
```
FetchError: request to https://npm-registry.foo.bar.com:1337//some-package failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (C:\tools\node\node_modules\npm-upgrade\node_modules\minipass-fetch\lib\index.js:97:14)
```

Any Idea how to fix this?

**Comment by antongolub** [comment]
@s-pic,

This doesn't seem to be a **npm-upgrade** problem. Here's a possible solution:
https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request

**Comment by s-pic** [comment]
Alright, thanks.
