### ISSUE TITLE
Allow partial updates

### ISSUE THREAD

**Issue by vjpr** [th0r/npm-upgrade#6]
The updates are all applied at once. It would be great if it applied them to the package.json file as you go.

**Comment by th0r** [comment]
Why do you need it?

**Comment by vjpr** [comment]
I had about 100 modules that needed updating and ran into this issue: https://github.com/th0r/npm-upgrade/issues/5 which meant I had to do it all again.

**Comment by vjpr** [comment]
Also, say I find a module that requires a major version update...such as babel 5 -> 6, or bluebird 2 -> 3. This module may require a huge refactor of my code and a bunch of commits, and possibly updating other modules.

When I come across something like this, I want to be able to commit all existing upgrades to package.json, and come back to it later.

**Comment by th0r** [comment]
> I had about 100 modules that needed updating and ran into this issue: #5 which meant I had to do it all again.

Sorry to hear that but it's an exceptional case (at least I hope so 😄)

> When I come across something like this, I want to be able to commit all existing upgrades to package.json, refactor my code, and come back to it later.

In this case I just answer `No` and continue. After that you can run `npm-upgrade` again.

Maybe it will be better to add `Finish upgrade` option to the end of the list?

**Comment by vjpr** [comment]
> Maybe it will be better to add Finish upgrade option to the end of the list?

I like it.

**Comment by th0r** [comment]
Added in `v1.0.1`
