### ISSUE TITLE
Support NPM 7 Workspaces

### ISSUE THREAD

**Issue by elkevinwolf** [th0r/npm-upgrade#62]
It would be awesome if this library could support [NPM 7 Workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces), allowing its users to easily upgrade dependencies in a monorepo project.

**Comment by eagleera** [comment]
any progress on this?

**Comment by antongolub** [comment]
As a workaround for now: https://github.com/antongolub/npm-upgrade-monorepo
