### ISSUE TITLE
Babel Changelog URL ist outdated

### ISSUE THREAD

**Issue by GarreltMock** [th0r/npm-upgrade#76]
Babel Upgrades point to the old Changelog: https://github.com/babel/babel/blob/master/CHANGELOG.md
This is the new one: https://github.com/babel/babel/blob/main/CHANGELOG.md

The branch name changed from master to main.

**Comment by th0r** [comment]
It would be great if you could submit a PR to fix the URL. Take a look at the last paragraph here please: https://github.com/th0r/npm-upgrade#troubleshooting

**Comment by GarreltMock** [comment]
Sure :) https://github.com/th0r/npm-upgrade/pull/77
Also added vue-loader changelog which was missing.

Though I did not update the changelog for all the babel packages.
Are wildcards possible in the changelogUrls.json?

**Comment by th0r** [comment]
Fixed in #77

**Comment by th0r** [comment]
> Are wildcards possible in the changelogUrls.json?
Unfortunately no, but feel free to implement this feature and open a PR 😉

**Comment by GarreltMock** [comment]
If I find some time I would love to contribute 😊  We will see. 
Thank you for merging.
